# This workflow will automatically build the project with Gradle
# It will run on every push and submitted PR.
# Acts as a first line of defense for invalid commits.

name: Build
on:
    push:
        paths-ignore:
            - '**.md'
            - '.gitignore'
            - '.github/**'
    pull_request:
        paths-ignore:
            - '**.md'
            - '.gitignore'
            - '.github/**'


jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: gradle
        
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
        
      - name: build with gradle
        run: ./gradlew buildAllVersions --stacktrace
          
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: versions/**/build/libs/*.jar
