name: Build and release
on: [ workflow_dispatch ]
jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 21 ]
        os: [ ubuntu-22.04 ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: release with gradle
        uses: Wandalen/wretry.action@master
        with:
          command: ./gradlew releaseAllVersions --stacktrace
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMIDE_MAVEN_USER: ${{ secerts.IMIDE_MAVEN_USER }}
          IMIDE_MAVEN_PASS: ${{ secerts.IMIDE_MAVEN_PASS }}

